### ISSUE TITLE
Blogroll

### ISSUE THREAD

**Issue by Tazinho** [rusershamburg/rusershamburg.github.io#14]
Maybe we could create a blogroll linking all r-bloggers from hamburg like here (top right): http://www.malte-grosser.com/

**Comment by henningsway** [comment]
i like it. Hopefully it will lead to more than a few blogs of the organizers. :)

**Comment by petermeissner** [comment]
Nice.

Henning <notifications@github.com> schrieb am Sa., 5. Mai 2018, 16:52:

**Comment by henningsway** [comment]
[] henningway.rbind.io ;)

**Comment by strengejacke** [comment]
I updated my Blogroll: https://strengejacke.wordpress.com
Anyone else here to be added?

**Comment by petermeissner** [comment]
I will close this now since blogroll is implemented and works. 

Feel free to add yourself or others to the blogroll directly in the blogroll.html file here: https://github.com/rusershamburg/rusershamburg.github.io/blob/master/blogroll.html like this: https://github.com/rusershamburg/rusershamburg.github.io/commit/faea8bc35129bca4167dfc6d95f759396e588f54 or ping me. Changes should become live ~10 secs after the commit.

**Comment by Tazinho** [comment]
Maybe we can add @kruse-alex new http://www.alexknowsdata.com/ also to our blogroll?

@petermeissner will you be on our next R Usergroup? I would like to mention our website again and at least the blogroll. Would you like to say some words about the website, perhaps it is more interesting to hear sth. from your side with a bit more background (kind of a quick overview how it is build, what it does and what plans we have or whatever you prefer ;)

**Comment by petermeissner** [comment]
1. Jep , will add it.
2. Jep I will be there, and I can say a few sentences ... 👍

Tazinho <notifications@github.com> schrieb am Mo., 4. Juni 2018, 14:50:
